complete javascript-timers
aehrenkranz/m2-1023-code-solutions pull request #3
Opened 2023-10-24 04:46 UTC by aehrenkranz

![capture2](https://github.com/aehrenkranz/m2-1023-code-solutions/assets/130402253/641dda07-926f-4d2a-a16c-f616115cc2ac)
![capture1](https://github.com/aehrenkranz/m2-1023-code-solutions/assets/130402253/d3603b92-958d-4910-b61c-36d5b04d07fc)

2023-10-24 23:08 UTC, ninajhun requested changes

2023-10-24 23:08 UTC, ninajhun commented on javascript-timers/javascript-timers/interval.js
Per step 7, **we need to countdown from 4,** i.e `4 , 3, 2, 1 ,'~Earth Beeeelooowww Us~'`. 

Otherwise, the syntax for setting and clearing an interval are correct! Lmk if you have any questions in slack!

2023-10-25 00:03 UTC, ninajhun requested changes

2023-10-25 00:03 UTC, ninajhun commented on javascript-timers/javascript-timers/interval.js
> +  }
This interval is unnecessary! You are starting a new interval but immediately clear it. So you are essentially doing nothing in this `if statement` in the end

2023-10-25 00:03 UTC, ninajhun commented on javascript-timers/javascript-timers/interval.js
**Suggestion:** Instead of checking for the text content, we can use a variable to keep track of the countdown value. This way we can just change this variable to another desired starting value such as 50 or 100!

2023-10-25 00:03 UTC, ninajhun commented on javascript-timers/javascript-timers/interval.js
**Tip:** When using intervals, we want to set the interval once and let it run until a certain condition is met! In this case, when the counter variable reaches 1 and then the text content is set to ` ~"Earth Beeeelooowww Us"~` to indicate the end of the countdown.

2023-10-25 00:35 UTC, aehrenkranz commented on javascript-timers/javascript-timers/interval.js
![Capture](https://github.com/aehrenkranz/m2-1023-code-solutions/assets/130402253/698d9ef4-bb18-4f55-9ef3-851d6316dec3)
Thank you for the suggestions. I've updated the code and added a new commit per said suggestions.

2023-10-25 01:38 UTC, ninajhun approved these changes
Good job on the changes!

2023-10-25 02:16 UTC, merged